name: Deploy to IPFS with Pinata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload to Pinata
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.2.0
        with:
          pinata_api_key: ${{ secrets.PINATA_API_KEY }}
          pinata_secret_api_key: ${{ secrets.PINATA_SECRET_API_KEY }}
          path: './my-website'
